runtime: nodejs20

#service: tracks

instance_class: F2

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

handlers:

  - url: /click-accent.wav
    static_files: dist/click-accent.wav
    upload: dist/click-accent.wav

  - url: /click.wav
    static_files: dist/click.wav
    upload: dist/click.wav

  - url: /img
    static_dir: dist/img

  - url: /js
    static_dir: dist/js

  - url: /css
    static_dir: dist/css

  - url: /favicon.ico
    static_files: dist/favicon.ico
    upload: dist/favicon.ico

  - url: /(.*\.(json|ico|html))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico|html)$

  - url: /.*
    script: auto