name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - run: NODE_OPTIONS=--openssl-legacy-provider npm ci
      - run: NODE_OPTIONS=--openssl-legacy-provider npm run build --if-present
      - run: NODE_OPTIONS=--openssl-legacy-provider npm test
